name: Auto Release Assets

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up tag and release name
        id: tagger
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          DATE=$(date +'%Y%m%d-%H%M%S')
          TAG="auto-release-${DATE}-${SHORT_SHA}"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          echo "RELEASE_NAME=$TAG" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            merge.bat
            replay.cfg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
